services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: ch
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=shop
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ch_data:/var/lib/clickhouse

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - clickhouse

  generator:
    build: ./generator
    container_name: generator
    restart: unless-stopped
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_QUEUE=events_q
      - SCENARIO=normal
      - EVENTS_PER_MIN=1800
      - SEED=42
    depends_on:
      - rabbitmq

  collector:
    build: ./collector
    container_name: collector
    restart: unless-stopped
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_QUEUE=events_q
      - CH_URL=http://clickhouse:8123
      - CH_USER=admin
      - CH_PASSWORD=admin
      - BATCH_SIZE=1500
      - FLUSH_SECS=2
    depends_on:
      - rabbitmq
      - clickhouse

volumes:
  ch_data:
  grafana_data:
